import { LucideIcon, Droplet, Mountain, Anchor, MoveRight, Type, Search, Bug, Hash, Calculator, Cpu, Bot, PlusCircle, Plus, Copy, Crown, Layers, ScanEye, Braces, Repeat, GitMerge, RefreshCw, Scissors, Shuffle, Grid, Phone, Target, Binary } from 'lucide-react';
import { ProblemId } from '../types/Problem';

export const PROBLEM_ICONS: Record<ProblemId, LucideIcon> = {
  'container-water': Droplet,
  'mountain-array': Mountain,
  'boats-people': Anchor,
  'move-zeroes': MoveRight,
  'longest-substring': Type,
  'find-position': Search,
  'first-bad-version': Bug,
  'missing-number': Hash,
  'count-primes': Calculator,
  'single-number': Cpu,
  'robot-return': Bot,
  'add-binary': PlusCircle,
  'two-sum': Plus,
  'contains-duplicate': Copy,
  'majority-element': Crown,
  'four-sum-ii': Layers,
  'min-window-substring': ScanEye,
  'group-anagrams': Braces,
  'lru-cache': Repeat,
  'merge-two-lists': GitMerge,
  'linked-list-cycle': RefreshCw,
  'reverse-linked-list': RefreshCw,
  'add-two-numbers': Plus,
  'remove-nth-node': Scissors,
  'odd-even-linked-list': Shuffle,
  'subsets': Grid,
  'letter-combinations': Phone,
  'combination-sum': Target,
  'palindrome-partition': Scissors,
  'symmetric-tree': Binary,
};
